### ISSUE TITLE
comments in macro processor are interpreted by macroprocessor

### ISSUE THREAD

**Issue by houtanb** [DynareTeam/dynare-preprocessor#4]
a `.mod` file with the lines
```
@#define x = 1
@{x}//@{x}
@{x}/*@{x}
*/
```
results in the macro expanded `.mod` file
```
1//1
1/*1
*/
```
It should be
```
1//@{x}
1/*@{x}
*/
```

**Comment by svillemot** [comment]
Note that the right solution is non-trivial, because you need to handle correctly cases such as:
```
my_matlab_string = 'foo
@#define a = [ "a", "b" ]
@#for i in a
@{a}
@#endfor
bar';
```
(note that the MATLAB string is opened before the macro-commands and closed after)

**Comment by houtanb** [comment]
Comments are now only allowed in statements.

Though multi-line strings are not supported in Matlab, the argument still holds for something of the form: `'a b // rest of string '`. 

They cannot be inside `@#for` loops because it could potentially ruin a string as above.
